In [3]:
import pandas as pd
from pymongo import MongoClient

In [4]:
# Se connecter à MongoDB
client = MongoClient('mongodb://localhost:27017/')

In [5]:

db = client['velibe']

In [6]:
# Sélectionner la collection
collection = db['collection_velibe']

In [7]:
# Récupérer toutes les données de la collection sous forme de liste de dictionnaires
data = list(collection.find())

In [9]:
# Afficher les données avec Pandas
df = pd.DataFrame(data)
df.head(10)

,_id,stationcode,name,is_installed,capacity,numdocksavailable,numbikesavailable,mechanical,ebike,is_renting,is_returning,duedate,coordonnees_geo,nom_arrondissement_communes,code_insee_commune
0,6643d9f8c469d48b125f6db3,9020,Toudouze - Clauzel,OUI,21,16,5,3,2,OUI,OUI,2024-05-14T20:45:33+00:00,"{'lon': 2.3373600840568547, 'lat': 48.87929591...",Paris,None
1,6643d9f8c469d48b125f6db4,14111,Cassini - Denfert-Rochereau,OUI,25,23,2,1,1,OUI,OUI,2024-05-14T20:52:24+00:00,"{'lon': 2.3360354080796, 'lat': 48.837525839067}",Paris,None
2,6643d9f8c469d48b125f6db5,14014,Jourdan - Stade Charléty,OUI,60,51,5,2,3,OUI,OUI,2024-05-14T20:52:18+00:00,"{'lon': 2.3433353751898, 'lat': 48.819428333369}",Paris,None
3,6643d9f8c469d48b125f6db6,32017,Basilique,OUI,22,5,13,9,4,OUI,OUI,2024-05-14T20:52:12+00:00,"{'lon': 2.3588666820200914, 'lat': 48.93626891...",Saint-Denis,None
4,6643d9f8c469d48b125f6db7,11104,Charonne - Robert et Sonia Delaunay,OUI,20,11,9,7,2,OUI,OUI,2024-05-14T20:49:47+00:00,"{'lon': 2.3925706744194, 'lat': 48.855907555969}",Paris,None
5,6643d9f8c469d48b125f6db8,8026,Messine - Place Du Pérou,OUI,12,11,0,0,0,OUI,OUI,2024-05-14T20:50:01+00:00,"{'lon': 2.315508019010038, 'lat': 48.875448033...",Paris,None
6,6643d9f8c469d48b125f6db9,13007,Le Brun - Gobelins,OUI,48,27,21,17,4,OUI,OUI,2024-05-14T20:51:23+00:00,"{'lon': 2.3534681351338, 'lat': 48.835092787824}",Paris,None
7,6643d9f8c469d48b125f6dba,7002,Vaneau - Sèvres,OUI,35,12,21,19,2,OUI,OUI,2024-05-14T20:50:28+00:00,"{'lon': 2.3204218259346, 'lat': 48.848563233059}",Paris,None
8,6643d9f8c469d48b125f6dbb,5110,Lacépède - Monge,OUI,23,20,3,0,3,OUI,OUI,2024-05-14T20:48:16+00:00,"{'lon': 2.3519663885235786, 'lat': 48.84389286...",Paris,None
9,6643d9f8c469d48b125f6dbc,6108,Saint-Romain - Cherche-Midi,OUI,17,17,0,0,0,OUI,OUI,2024-05-14T20:44:59+00:00,"{'lon': 2.321374788880348, 'lat': 48.847081590...",Paris,None

EDA

In [11]:
df .describe()

,capacity,numdocksavailable,numbikesavailable,mechanical,ebike
count,3260.000000,3260.000000,3260.000000,3260.000000,3260.000000
mean,30.887117,17.750613,12.017178,7.159509,4.857669
std,12.255093,14.584290,10.824509,9.286928,5.325259
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,22.000000,7.000000,3.000000,1.000000,1.000000
50%,29.000000,15.000000,9.000000,2.000000,3.000000
75%,37.000000,24.000000,20.000000,10.000000,8.000000
max,64.000000,60.000000,49.000000,48.000000,24.000000

In [12]:
taille=len(df)

In [13]:
print(taille)

3260